#!/bin/bash
source /usr/share/diskripper/config

#echo "autodisk " `date '+%s'` "$DEVNAME \n" > /home/${user}/.var/log/diskrip/.autodisk.log
{
  if [ "$ID_CDROM_MEDIA_BD" -eq "1" ]; then
    runuser -l $user -c "echo dvdrip ripdisk -e $DEVNAME | at now"
    exit 1
  fi
}
{
  if [ "$ID_CDROM_MEDIA_DVD" -eq "1" ]; then
    runuser -l $user -c "echo dvdrip ripdisk -m $DEVNAME | at now"
  fi
}
{
  if [ "$ID_CDROM_MEDIA_CD" -eq "1" ]; then
    runuser -l $user -c "echo cdrip $DEVNAME | at now"
  fi
}

