#!/bin/bash
source /usr/share/diskripper/config

echo "autodisk " `date '+%s'` "$DEVNAME \n" > /home/${user}/.var/log/diskrip/.messages.log
{
  if [ "$ID_CDROM_MEDIA_BD" -eq "1" ]; then
    runuser -l $user -c "echo dvdrip ripdisk -e $DEVNAME | at now"
    #echo "BD insert" > "/home/${user}/.var/log/diskrip/.insert" 
    exit 1
  fi
}
{
  if [ "$ID_CDROM_MEDIA_DVD" -eq "1" ]; then
    runuser -l $user -c "echo dvdrip ripdisk -m $DEVNAME | at now"
    #echo "dvd insert" > "/home/${user}/.var/log/diskrip/.insert" 
  fi
}
{
  if [ "$ID_CDROM_MEDIA_CD" -eq "1" ]; then
    runuser -l $user -c "echo cdrip $DEVNAME | at now"
    #echo "cd insert" > "/home/${user}/.var/log/diskrip/.insert" 
  fi
}

