#!/bin/bash
source /usr/share/diskripper/config

#set -x

device=$1

discname=$(blkid -o value -s LABEL $device)
discname=$(tr '_' ' ' <<<"$discname")
discname=$(echo "$discname" | tr '[:upper:]' '[:lower:]')
arr=( $discname )
discname=${arr[@]^}
logfile="/home/${user}/.var/log/diskrip/cd/${discname}.log"

install -o $user -g $user -d /home/${user}/.var/log/diskrip/cd/

sleep 2

runuser -l $user -c "echo `date '+%s'` > $logfile"

runuser -l $user -c "abcde -d $device >> $logfile"
