#!/bin/bash
source /usr/share/diskripper/config

#set -x

ripdir="${DVD_ripdir}"
encdir="${movie_outdir}"
outformat="${DVD_outformat}"

device=$1

echo `date '+%s'`" - starting dvdripper" >> /home/${user}/.var/log/diskrip/.messages.log

echo $device >> /home/${user}/.var/log/diskrip/.messages.log

logdir=/home/${user}/.var/log/diskrip/dvd/

#####

discname=$(blkid -o value -s LABEL $device)
discname=$(tr '_' ' ' <<<"$discname")
discname=$(echo "$discname" | tr '[:upper:]' '[:lower:]')
arr=( $discname )
discname=${arr[@]^}
logfile="${logdir}${discname}.log"

echo "ripping disc $discname" >> "$logfile"
echo "ripping disc $discname" >> /home/${user}/.var/log/diskrip/.messages.log

sleep 2;

makemkvcon --progress=stdout --minlength=2500 --decrypt mkv dev:$device all $ripdir >> "$logfile"; 

sleep 2;

# Rename Files

if [ ! -d "${remotedir}/${discname}" ]; then
  mkdir "${remotedir}/${discname}"
fi

numFiles=`find $ripdir -maxdepth 1 -iname '*.${outformat}' -printf x | wc -c`

i=1

find $ripdir -maxdepth 1 -iname '*.${outformat}' -print0 | sort -z | while IFS= read -r -d '' file; 
do 
   
    title=$(mkvinfo "${file}" | grep Title)
    title=${title:11}
    
    fileoutname="${discname}/${title}"

    if (( numFiles > 1 )); then
      fileoutname="${fileoutname}_$i"
      ((i=i+1))
    fi

    fileoutname="${fileoutname}.${outformat}"
    
    echo "Renaming $file to ${fileoutname}" >> "$logfile";

    mv "$file" "${remotedir}/${fileoutname}"

    echo "File = ${remotedir}/${fileoutname} ----  Disc = ${discname} ---- using:${namestatus}" >> "${logdir}riplist.txt"
done

sleep 2 ;
eject -r  $device
